fixtures:
  repositories:
    apache:           'https://github.com/theforeman/puppet-apache'
    passenger:        'https://github.com/theforeman/puppet-passenger'
    foreman:          'https://github.com/theforeman/puppet-foreman'
    git:              'https://github.com/theforeman/puppet-git'
    concat_native:    'https://github.com/theforeman/puppet-concat'
    stdlib:           'https://github.com/puppetlabs/puppetlabs-stdlib.git'

  symlinks:
    puppet: "#{source_dir}"
