fixtures:
  repositories:
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    concat:   'https://github.com/puppetlabs/puppetlabs-concat.git'
    cron_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core'
      puppet_version: '>= 6.0.0'
    extlib:               'https://github.com/voxpupuli/puppet-extlib.git'
    git:                  'https://github.com/theforeman/puppet-git.git'
    inifile:              'https://github.com/puppetlabs/puppetlabs-inifile.git'
    puppetdb:             'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
    puppetserver_foreman: 'https://github.com/theforeman/puppet-puppetserver_foreman.git'
    stdlib:               'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    systemd:              'https://github.com/camptocamp/puppet-systemd.git'
