fixtures:
  repositories:
    apache:           'https://github.com/puppetlabs/puppetlabs-apache.git'
    concat:           'https://github.com/puppetlabs/puppetlabs-concat.git'
    extlib:           'https://github.com/voxpupuli/puppet-extlib.git'
    foreman:          'https://github.com/theforeman/puppet-foreman.git'
    git:              'https://github.com/theforeman/puppet-git.git'
    hocon:            'https://github.com/puppetlabs/puppetlabs-hocon.git'
    inifile:          'https://github.com/puppetlabs/puppetlabs-inifile.git'
    puppetdb:         'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
    stdlib:           'https://github.com/puppetlabs/puppetlabs-stdlib.git'

  symlinks:
    puppet: "#{source_dir}"
