fixtures:
  repositories:
    augeas_core: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
    concat:   'https://github.com/puppetlabs/puppetlabs-concat.git'
    cron_core: 'https://github.com/puppetlabs/puppetlabs-cron_core'
    extlib:               'https://github.com/voxpupuli/puppet-extlib.git'
    git:                  'https://github.com/theforeman/puppet-git.git'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: 'ec56edb8901461324e656aea31541aa954d1c523'
    puppetdb:             'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
    puppetserver_foreman: 'https://github.com/theforeman/puppet-puppetserver_foreman.git'
    stdlib:               'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    systemd:              'https://github.com/voxpupuli/puppet-systemd.git'
    vcsrepo:              'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
