---
.travis.yml:
  beaker_sets:
    - centos6-64
    - debian9-64
    - debian10-64
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
  beaker_puppet_collections:
    - puppet5
    - puppet6
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
