---
.travis.yml:
  beaker_sets:
    - centos6-64
    - debian9-64
    - debian10-64
    - ubuntu1804-64
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
  beaker_puppet_collections:
    - puppet5
    - puppet6
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
Gemfile:
  extra:
    - gem: bolt
      version: '~> 1.15'
      # TODO: Add something to foreman-installer-modulesync to support `unless ENV['PUPPET_VERSION'] =~ /^5/`
      options:
        groups:
        - 'system_tests'
    - gem: beaker-task_helper
      version: '~> 1.7'
      options:
        groups:
        - 'system_tests'
