---
.github/workflows/acceptance.yml:
  excludes:
    - setfile: debian10-64{hostname=debian10-64.example.com}
      puppet: "5"
    - setfile: ubuntu2004-64{hostname=ubuntu2004-64.example.com}
      puppet: "5"
  pidfile_workaround: true
.github/workflows/cron.yml:
  excludes:
    - setfile: debian10-64{hostname=debian10-64.example.com}
      puppet: "5"
    - setfile: ubuntu2004-64{hostname=ubuntu2004-64.example.com}
      puppet: "5"
  pidfile_workaround: true
Gemfile:
  extra:
    - gem: hocon
