---
.travis.yml:
  beaker_sets:
    - centos7-64
    - centos6-64
    - debian8-64
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
  # Some upgrade tests rely on PC1 version numbers
  beaker_puppet_collection: pc1
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
spec/spec_helper.rb:
  extra_code: |
    aio = on_os_under_test.reject do |os, facts|
      ['FreeBSD', 'DragonFly', 'Windows'].include?(facts[:operatingsystem])
    end.keys

    add_custom_fact :rubysitedir, '/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0', :confine => aio

    def unsupported_puppetmaster_osfamily(osfamily)
      ['Archlinux', 'windows', 'Suse'].include?(osfamily)
    end
