---
.travis.yml:
  beaker_sets:
    - docker/centos-7
    - docker/centos-6
    - docker/debian-8
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
spec/spec_helper.rb:
  extra_code: |
    def unsupported_puppetmaster_osfamily(osfamily)
      ['Archlinux', 'windows', 'Suse'].include?(osfamily)
    end
spec/spec_helper_acceptance.rb:
  modules:
    - puppet-extlib
    - puppetlabs-apache
    - puppetlabs-concat
    - puppetlabs-hocon
    - puppetlabs-stdlib
