---
.travis.yml:
  beaker_sets:
    - docker/centos-7
    - docker/centos-6
    - docker/debian-8
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
spec/spec_helper.rb:
  extra_code: |
    aio = on_os_under_test.reject do |os, facts|
      ['FreeBSD', 'DragonFly', 'Windows'].include?(facts[:operatingsystem])
    end.keys

    add_custom_fact :rubysitedir, '/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.1.0', :confine => aio

    def unsupported_puppetmaster_osfamily(osfamily)
      ['Archlinux', 'windows', 'Suse'].include?(osfamily)
    end
