---
.travis.yml:
  beaker_sets:
    - centos-7-x64_docker
    - centos-6-x64_docker
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
Gemfile:
  extra:
    - gem: 'beaker-rspec'
      options:
        groups:
          - 'system_tests'
    - gem: 'beaker-puppet_install_helper'
      options:
        groups:
          - 'system_tests'
spec/spec_helper.rb:
  extra_code: |
    def unsupported_puppetmaster_osfamily(osfamily)
      ['Archlinux', 'windows', 'Suse'].include?(osfamily)
    end
