name    'theforeman-puppet'
version '1.2.0-rc1'
source 'git://github.com/theforeman/puppet-puppet'
author 'theforeman'
license 'GPLv3+'
summary 'Puppet agent and server configuration'
description 'Module for installing the Puppet agent and Puppet server'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'theforeman/apache', '>= 1.2.0-rc1'
dependency 'theforeman/concat_native', '>= 1.2.0-rc1'
dependency 'theforeman/git', '>= 1.2.0-rc1'
dependency 'theforeman/passenger', '>= 1.2.0-rc1'
